export const PROUDUCT_LIST_REQUEST ='PROUDUCT_LIST_REQUEST'
export const PROUDUCT_LIST_SUCCESS ='PROUDUCT_LIST_SUCCESS'
export const PROUDUCT_LIST_FAIL ='PROUDUCT_LIST_FAIL'



export const PROUDUCT_DETAILS_REQUEST ='PROUDUCT_DETAILS_REQUEST'
export const PROUDUCT_DETAILS_SUCCESS ='PROUDUCT_DETAILS_SUCCESS'
export const PROUDUCT_DETAILS_FAIL ='PROUDUCT_DETAILS_FAIL'


export const PRODUCT_ADD_REQUEST = 'PRODUCT_ADD_REQUEST'
export const PRODUCT_ADD_SUCCESS = 'PRODUCT_ADD_SUCCESS'
export const PRODUCT_ADD_FAIL = 'PRODUCT_ADD_FAIL'




export const PRODUCT_TOP_REQUEST = 'PRODUCT_TOP_REQUEST'
export const PRODUCT_TOP_SUCCESS = 'PRODUCT_TOP_SUCCESS'
export const PRODUCT_TOP_FAIL = 'PRODUCT_TOP_FAIL'



