# Generated by Django 3.2.6 on 2023-10-15 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='matricule',
            field=models.IntegerField(default=7),
            preserve_default=False,
        ),
    ]
