# Generated by Django 3.2.6 on 2024-01-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_order_orderitem_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='textPrice',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='address',
        ),
    ]
